apiVersion: v1
kind: Pod
metadata:
  name: nextflow-runner
spec:
  serviceAccountName: nextflow-sa
  containers:
  - name: nextflow
    image: nextflow/nextflow
    command: ["/bin/bash"]
    args: ["-c", "nextflow run https://github.com/YOUR-USER/YOUR-PIPELINE"]
    volumeMounts:
    - name: pvc
      mountPath: /mnt/pvc
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: nextflow-pvc
  restartPolicy: Never
